"use client";
import {useEffect,useMemo,useState} from "react";import{api,auth}from"../../lib/api";
export default function Admin(){const[user,setUser]=useState(null),[setup,setSetup]=useState(null),[username,setUsername]=useState("tempo-owner"),[password,setPassword]=useState(""),[validatorPassword,setValidatorPassword]=useState(""),[validatorName,setValidatorName]=useState("Tempo Door Staff"),[rows,setRows]=useState([]),[query,setQuery]=useState(""),[showTests,setShowTests]=useState(false),[detail,setDetail]=useState(null),[error,setError]=useState(""),[message,setMessage]=useState("");
useEffect(()=>{api("/setup/status").then(setSetup);auth.me().then(x=>setUser(x.user)).catch(()=>{})},[]);useEffect(()=>{if(user)load()},[user,showTests]);async function load(){try{setRows(await api(`/admin/entrants?include_tests=${showTests}`))}catch(e){setError(e.message)}}
async function setupOwner(e){e.preventDefault();try{await api("/setup/owner",{method:"POST",body:{password}});setSetup({...setup,owner_complete:1});setPassword("")}catch(e){setError(e.message)}}async function login(e){e.preventDefault();try{const x=await auth.login(username,password);setUser(x.user);setPassword("")}catch(e){setError(e.message)}}
async function createValidator(e){e.preventDefault();setError("");setMessage("");try{await api("/admin/validator",{method:"POST",body:{password:validatorPassword,display_name:validatorName}});setValidatorPassword("");setSetup({...setup,validator_complete:1});setMessage("Validator login created. Username: tempo-validator")}catch(e){setError(e.message)}}
const filtered=useMemo(()=>rows.filter(r=>`${r.preferred_name} ${r.whatsapp} ${r.entry_reference}`.toLowerCase().includes(query.toLowerCase())),[rows,query]),real=rows.filter(r=>!r.is_test),metrics={registrations:real.length,coming:real.filter(r=>r.rsvp_status==="coming").length,remind_later:real.filter(r=>r.rsvp_status==="remind_later").length,expected_guests:real.filter(r=>r.rsvp_status==="coming").reduce((n,r)=>n+(r.party_size||1),0),checked_in:real.filter(r=>r.checked_in_at).length,marketing_opt_ins:real.filter(r=>r.marketing_consent).length};
async function toggleTest(r){await api(`/admin/entrants/${r.id}/test`,{method:"PATCH",body:{is_test:!r.is_test}});load();setDetail({...r,is_test:!r.is_test})}async function logout(){await auth.logout();setUser(null)}
if(setup&&!setup.owner_complete)return <main className="portal"><section className="login-card"><p className="eyebrow">ONE-TIME SECURE SETUP</p><h1>Create owner access.</h1><p className="lead">Username: <strong>tempo-owner</strong>. Enter the password saved privately in Bitwarden. Only a scrypt hash is stored.</p><form onSubmit={setupOwner}><label>Bitwarden password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/><button className="register-button">CREATE OWNER LOGIN</button></form>{error&&<p className="error">{error}</p>}</section></main>;
if(!user)return <main className="portal"><section className="login-card"><p className="eyebrow">OWNER ACCESS</p><h1>Tempo Pass<br/>command centre.</h1><form onSubmit={login}><label>Username</label><input value={username} onChange={e=>setUsername(e.target.value)}/><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="register-button">LOG IN</button></form>{error&&<p className="error">{error}</p>}</section></main>;
return <main className="portal"><section className="dashboard"><header className="dash-head"><div><p className="eyebrow">OWNER DASHBOARD</p><h1>Tempo Pass</h1></div><button className="secondary-button" onClick={logout}>Log out</button></header><div className="metrics">{Object.entries(metrics).map(([k,v])=><article key={k}><strong>{v}</strong><span>{k.replaceAll("_"," ")}</span></article>)}</div>{setup&&!setup.validator_complete&&<form className="validator-setup" onSubmit={createValidator}><div><p className="eyebrow">ONE-TIME STAFF SETUP</p><h2>Create validator access</h2><p>Fixed username: <strong>tempo-validator</strong>. Use a separate Bitwarden password. Staff never receives owner access.</p></div><label>Staff display name<input value={validatorName} onChange={e=>setValidatorName(e.target.value)}/></label><label>Validator password<input type="password" value={validatorPassword} onChange={e=>setValidatorPassword(e.target.value)} autoComplete="new-password"/></label><button className="register-button">CREATE VALIDATOR LOGIN</button></form>}{message&&<p className="success">{message}</p>}{error&&<p className="error">{error}</p>}<div className="toolbar"><input placeholder="Search name, WhatsApp or reference" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={showTests} onChange={e=>setShowTests(e.target.checked)}/> Show test entries</label><a className="secondary-button link-button" href="/api/admin/export.csv">Export CSV</a></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>WhatsApp</th><th>Pass / prize</th><th>RSVP</th><th>Guests</th><th>Check-in</th><th>Registered</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} onClick={()=>setDetail(r)} className={r.is_test?"test-row":""}><td>{r.preferred_name}{r.is_test&&" · TEST"}</td><td>{r.whatsapp}</td><td>{r.tier} · {r.instant_prize}</td><td>{r.rsvp_status}</td><td>{r.party_size}</td><td>{r.checked_in_at?"Yes":"No"}</td><td>{new Date(r.registered_at).toLocaleString("en-GB",{timeZone:"Asia/Bangkok"})}</td></tr>)}</tbody></table></div>{detail&&<div className="detail"><button onClick={()=>setDetail(null)}>×</button><h2>{detail.preferred_name}</h2><button className="secondary-button" onClick={()=>toggleTest(detail)}>{detail.is_test?"MARK AS REAL ENTRY":"MARK AS TEST ENTRY"}</button>{Object.entries(detail).map(([k,v])=><p key={k}><strong>{k.replaceAll("_"," ")}</strong><span>{Array.isArray(v)?v.join(", "):String(v??"—")}</span></p>)}</div>}</section></main>}
