import test from "node:test";import assert from "node:assert/strict";import request from "supertest";import{openDatabase}from"../server/db.js";import{createApp}from"../server/app.js";import{getByToken,hashToken,isTestEntrant,register}from"../server/core.js";import{normalizeCode,normalizeWhatsApp,eventCalendarHref,csvEscape}from"../lib/pass.js";
function fixture(){const db=openDatabase(":memory:"),app=createApp({db,staticDir:"dist/client",secureCookies:false});return{db,app}}
test("shared codes and WhatsApp validation",()=>{assert.equal(normalizeCode("g001"),"G-001");assert.equal(normalizeCode("G-002"),"");assert.equal(normalizeWhatsApp("+66 81-234-5678"),"+66812345678")});
test("multiple entrants can use same shared code and get distinct opaque tokens",()=>{const{db}=fixture(),a=register(db,{shared_code:"G-001",preferred_name:"A",whatsapp:"+66810000001",required_consent:true}),b=register(db,{shared_code:"G-001",preferred_name:"B",whatsapp:"+66810000002",required_consent:true});assert.notEqual(a.entry_reference,b.entry_reference);assert.notEqual(a.manage_token,b.manage_token);assert.equal(db.prepare("select count(*) n from entrants where shared_code='G-001'").get().n,2);assert.equal(db.prepare("select qr_token_hash from entrants where id=?").get(a.id).qr_token_hash,hashToken(a.manage_token));assert.doesNotMatch(JSON.stringify(db.prepare("select * from entrants where id=?").get(a.id)),new RegExp(a.manage_token))});
test("test detection catches Milhouse variants and configured number hashes",()=>{assert.equal(isTestEntrant("Milhousen batch","+661"),true);assert.equal(isTestEntrant("Real guest","+662",[hashToken("+662")]),true);assert.equal(isTestEntrant("Real guest","+663"),false)});
test("registration validates consent and treat selection",()=>{const{db}=fixture();assert.throws(()=>register(db,{shared_code:"T-001",preferred_name:"X",whatsapp:"+66810000003",required_consent:true}),/Choose/);assert.throws(()=>register(db,{shared_code:"G-001",preferred_name:"X",whatsapp:"+66810000003",required_consent:false}),/consent/)});
test("setup is one-time, password hashed, auth and CSRF enforced",async()=>{const{db,app}=fixture(),agent=request.agent(app);await agent.post("/api/setup/owner").send({password:"StrongExamplePassword!123"}).expect(200);await agent.post("/api/setup/owner").send({password:"AnotherStrongPassword!456"}).expect(409);assert.doesNotMatch(db.prepare("select password_hash from app_users").get().password_hash,/StrongExample/);const login=await agent.post("/api/auth/login").send({username:"tempo-owner",password:"StrongExamplePassword!123"}).expect(200);await agent.patch("/api/admin/entrants/nope/test").send({is_test:true}).expect(403);await agent.patch("/api/admin/entrants/nope/test").set("X-CSRF-Token",login.body.csrf).send({is_test:true}).expect(200)});
test("owner setup accepts a 14-character Bitwarden password and rejects shorter passwords",async()=>{const short=fixture();await request(short.app).post("/api/setup/owner").send({password:"1234567890123"}).expect(400);const exact=fixture();await request(exact.app).post("/api/setup/owner").send({password:"Ab3!5678901234"}).expect(200)});
test("owner and anonymous authorization for list and CSV",async()=>{const{app}=fixture(),agent=request.agent(app);await request(app).get("/api/admin/entrants").expect(401);await request(app).get("/api/admin/export.csv").expect(401);await agent.post("/api/setup/owner").send({password:"StrongExamplePassword!123"});await agent.post("/api/auth/login").send({username:"tempo-owner",password:"StrongExamplePassword!123"});await agent.get("/api/admin/entrants").expect(200);await agent.get("/api/admin/export.csv").expect(200).expect("Content-Type",/csv/)});
test("registration API, RSVP and recovery rotate token",async()=>{const{db,app}=fixture();const reg=await request(app).post("/api/register").send({shared_code:"R-001",preferred_name:"Guest",whatsapp:"+66810000004",required_consent:true}).expect(201);await request(app).patch(`/api/pass/${reg.body.manage_token}`).send({rsvp_status:"coming",party_size:4,interests:["Karaoke"]}).expect(200).expect(r=>assert.equal(r.body.party_size,4));const old=reg.body.manage_token,rec=await request(app).post("/api/recover").send({entry_reference:reg.body.entry_reference,whatsapp:"+66810000004"}).expect(200);assert.ok(rec.body.manage_token);assert.equal(getByToken(db,old),null);assert.ok(getByToken(db,rec.body.manage_token));const miss=await request(app).post("/api/recover").send({entry_reference:"bad",whatsapp:"+66810000004"}).expect(200);assert.equal(miss.body.manage_token,undefined)});
test("validator sees minimum data, requires physical pass and prevents duplicate check-in",async()=>{const{app}=fixture(),owner=request.agent(app),staff=request.agent(app);const reg=(await request(app).post("/api/register").send({shared_code:"G-001",preferred_name:"Guest",whatsapp:"+66810000005",required_consent:true})).body;await owner.post("/api/setup/owner").send({password:"StrongExamplePassword!123"});const ol=await owner.post("/api/auth/login").send({username:"tempo-owner",password:"StrongExamplePassword!123"});await owner.post("/api/admin/validator").set("X-CSRF-Token",ol.body.csrf).send({password:"ValidatorPassword!123",display_name:"Door Staff"}).expect(200);const sl=await staff.post("/api/auth/login").send({username:"tempo-validator",password:"ValidatorPassword!123"}).expect(200);const lookup=await staff.post("/api/validate/lookup").set("X-CSRF-Token",sl.body.csrf).send({token:reg.manage_token}).expect(200);assert.equal(lookup.body.whatsapp,undefined);await staff.post("/api/validate/check-in").set("X-CSRF-Token",sl.body.csrf).send({token:reg.manage_token,physical_pass_confirmed:false}).expect(400);const first=await staff.post("/api/validate/check-in").set("X-CSRF-Token",sl.body.csrf).send({token:reg.manage_token,physical_pass_confirmed:true}).expect(200);assert.equal(first.body.already_checked_in,false);const second=await staff.post("/api/validate/check-in").set("X-CSRF-Token",sl.body.csrf).send({token:reg.manage_token,physical_pass_confirmed:true}).expect(200);assert.equal(second.body.already_checked_in,true)});
test("CSV and calendar safety",()=>{assert.equal(csvEscape("=BAD"),"'=BAD");const c=decodeURIComponent(eventCalendarHref());assert.match(c,/20260822/);assert.match(c,/time to be confirmed/i)});
