import express from "express";
import { randomBytes } from "node:crypto";
import { openDatabase } from "./db.js";
import { audit, checkIn, getByToken, hashPassword, hashToken, hydrate, recover, register, updatePreferences, verifyPassword } from "./core.js";

const json=express.json({limit:"32kb"}); const cookie=(req,name)=>req.headers.cookie?.split(";").map(x=>x.trim().split("=")).find(x=>x[0]===name)?.[1];
export function createApp({db=openDatabase(),staticDir="dist/client",pageHandler=null,secureCookies=process.env.NODE_ENV==="production"}={}){
 const app=express();app.disable("x-powered-by");app.use((req,res,next)=>{res.set({"X-Content-Type-Options":"nosniff","Referrer-Policy":"same-origin","X-Frame-Options":"DENY","Permissions-Policy":"camera=(self)","Content-Security-Policy":"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self';"});next()});app.use("/api",json);
 const rates=new Map();function limited(req,res,next){const k=req.ip+req.path,n=Date.now(),x=rates.get(k)||{n:0,t:n};if(n-x.t>60000){x.n=0;x.t=n}if(++x.n>20)return res.status(429).json({error:"Too many attempts. Please wait and try again."});rates.set(k,x);next()}
 const session=(req,res,next)=>{const id=cookie(req,"tempo_session"),s=id&&db.prepare("SELECT s.*,u.username,u.role,u.display_name FROM sessions s JOIN app_users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?").get(id,new Date().toISOString());if(!s)return res.status(401).json({error:"Authentication required."});req.user=s;if(!["GET","HEAD"].includes(req.method)&&req.headers["x-csrf-token"]!==s.csrf_token)return res.status(403).json({error:"Security token mismatch."});next()}; const role=(...roles)=>(req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:"Not authorized."});
 app.get("/api/setup/status",(_q,res)=>res.json(db.prepare("SELECT owner_complete,validator_complete FROM setup_state WHERE id=1").get()));
 app.post("/api/setup/owner",limited,(req,res)=>{const state=db.prepare("SELECT owner_complete FROM setup_state WHERE id=1").get();if(state.owner_complete)return res.status(409).json({error:"Owner setup is already complete."});const p=String(req.body.password||"");if(p.length<14)return res.status(400).json({error:"Use your strong Bitwarden password (minimum 14 characters)."});db.transaction(()=>{db.prepare("INSERT INTO app_users(username,password_hash,role,display_name,created_at) VALUES(?,?,?,?,?)").run("tempo-owner",hashPassword(p),"owner","Tempo Owner",new Date().toISOString());db.prepare("UPDATE setup_state SET owner_complete=1 WHERE id=1").run()})();res.json({ok:true,username:"tempo-owner"})});
 app.post("/api/auth/login",limited,(req,res)=>{const u=db.prepare("SELECT * FROM app_users WHERE username=? AND active=1").get(String(req.body.username||""));if(!u||!verifyPassword(String(req.body.password||""),u.password_hash))return res.status(401).json({error:"Invalid username or password."});const id=randomBytes(32).toString("base64url"),csrf=randomBytes(24).toString("base64url"),at=new Date(),exp=new Date(at.getTime()+8*3600000);db.prepare("INSERT INTO sessions VALUES(?,?,?,?,?)").run(id,u.id,csrf,exp.toISOString(),at.toISOString());res.setHeader("Set-Cookie",`tempo_session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${secureCookies?"; Secure":""}`);res.json({user:{username:u.username,role:u.role,display_name:u.display_name},csrf})});
 app.post("/api/auth/logout",session,(req,res)=>{db.prepare("DELETE FROM sessions WHERE id=?").run(req.user.id);res.setHeader("Set-Cookie","tempo_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0");res.json({ok:true})});app.get("/api/auth/me",session,(req,res)=>res.json({user:{username:req.user.username,role:req.user.role,display_name:req.user.display_name},csrf:req.user.csrf_token}));
 app.post("/api/register",limited,(req,res)=>{try{res.status(201).json(register(db,req.body,{testHashes:(process.env.TEMPO_TEST_NUMBER_HASHES||"").split(",").filter(Boolean)}))}catch(e){res.status(e.status||500).json({error:e.message})}});
 app.get("/api/pass/:token",limited,(req,res)=>{const r=getByToken(db,req.params.token);r?res.json(publicRow(r)):res.status(404).json({error:"Pass not found."})});
 app.patch("/api/pass/:token",limited,(req,res)=>{try{res.json(publicRow(updatePreferences(db,req.params.token,req.body)))}catch(e){res.status(e.status||500).json({error:e.message})}});
 app.post("/api/recover",limited,(req,res)=>{const r=recover(db,req.body.entry_reference,req.body.whatsapp);res.json({message:"If those details match, a fresh pass link is ready.",...(r||{})})});
 app.get("/api/admin/entrants",session,role("owner"),(req,res)=>{const include=req.query.include_tests==="true";res.json(db.prepare(`SELECT * FROM entrants ${include?"":"WHERE is_test=0"} ORDER BY registered_at DESC`).all().map(hydrate))});
 app.patch("/api/admin/entrants/:id/test",session,role("owner"),(req,res)=>{db.prepare("UPDATE entrants SET is_test=?,updated_at=? WHERE id=?").run(req.body.is_test?1:0,new Date().toISOString(),req.params.id);audit(db,"owner",String(req.user.user_id),"entrant.test_status_changed",req.params.id,{is_test:!!req.body.is_test});res.json({ok:true})});
 app.get("/api/admin/export.csv",session,role("owner"),(req,res)=>{const rows=db.prepare("SELECT * FROM entrants ORDER BY registered_at DESC").all().map(hydrate),fields=["preferred_name","whatsapp","tier","instant_prize","entry_reference","registered_at","marketing_consent","rsvp_status","party_size","checked_in_at","is_test"];const esc=v=>`"${String(v??"").replace(/^([=+\-@])/,"'$1").replaceAll('"','""')}"`;res.type("text/csv").send([fields.join(","),...rows.map(r=>fields.map(f=>esc(r[f])).join(","))].join("\n"))});
 app.post("/api/admin/validator",session,role("owner"),(req,res)=>{if(db.prepare("SELECT 1 FROM app_users WHERE role='validator'").get())return res.status(409).json({error:"Validator credential already exists."});const p=String(req.body.password||"");if(p.length<14)return res.status(400).json({error:"Password must be at least 14 characters."});db.prepare("INSERT INTO app_users(username,password_hash,role,display_name,created_at) VALUES(?,?,?,?,?)").run("tempo-validator",hashPassword(p),"validator",String(req.body.display_name||"Tempo Staff").slice(0,60),new Date().toISOString());db.prepare("UPDATE setup_state SET validator_complete=1 WHERE id=1").run();res.json({ok:true,username:"tempo-validator"})});
 app.post("/api/validate/lookup",session,role("validator","owner"),(req,res)=>{let r=req.body.token?getByToken(db,req.body.token):db.prepare("SELECT * FROM entrants WHERE upper(entry_reference)=upper(?) AND whatsapp=?").get(req.body.entry_reference,req.body.whatsapp);if(!r)return res.status(404).json({error:"No matching entry."});res.json(staffRow(hydrate(r)))});
 app.post("/api/validate/check-in",session,role("validator","owner"),(req,res)=>{let r=req.body.token?getByToken(db,req.body.token):db.prepare("SELECT * FROM entrants WHERE upper(entry_reference)=upper(?) AND whatsapp=?").get(req.body.entry_reference,req.body.whatsapp);if(!r)return res.status(404).json({error:"No matching entry."});if(req.body.physical_pass_confirmed!==true)return res.status(400).json({error:"Confirm the original physical Tempo Pass first."});res.json(staffRow(checkIn(db,r,req.user)))});
 app.use(express.static(staticDir));if(pageHandler)app.use(async(req,res,next)=>{try{const origin=`${req.protocol}://${req.get("host")}`,request=new Request(new URL(req.originalUrl,origin),{method:req.method,headers:req.headers});const out=await pageHandler(request);res.status(out.status);out.headers.forEach((v,k)=>res.setHeader(k,v));res.send(Buffer.from(await out.arrayBuffer()))}catch(e){next(e)}});app.locals.db=db;return app;
}
function publicRow(r){return {entry_reference:r.entry_reference,preferred_name:r.preferred_name,shared_code:r.shared_code,tier:r.tier,instant_prize:r.instant_prize,treat_choice:r.treat_choice,rsvp_status:r.rsvp_status,party_size:r.party_size,interests:r.interests,whatsapp_updates:r.whatsapp_updates,checked_in_at:r.checked_in_at}}
function staffRow(r){return {id:r.id,entry_reference:r.entry_reference,preferred_name:r.preferred_name,tier:r.tier,instant_prize:r.instant_prize,treat_choice:r.treat_choice,checked_in_at:r.checked_in_at,checked_in_by:r.checked_in_by,already_checked_in:r.already_checked_in}}
